const  express = require('express');
const { Agent } = require('http');
const app = express();
const port = 3000;
const axios =  require('axios');

const swaggerJsdoc = require('swagger-jsdoc')
const swaggerUi = require('swagger-ui-express');
const cors = require('cors');
app.use(express.json());
const options = {
  swaggerDefinition: {
   info: {
       title: 'Personal Budget API',
       version: '1.0.0',
       description: 'Personal Budget API autogenerated by Swagger'
   },
   host: '159.203.174.246:3000',
   basePath: '/',
  },
  apis: ['./routes.js'],
};

app.use(cors());
const specs = swaggerJsdoc(options);
app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));
require('./routes')(app);

app.get('/say', (req,res) => {
  let keyword = req.query.keyword || 'empty'
  axios.get(`https://faas-nyc1-2ef2e6cc.doserverless.co/api/v1/web/fn-045ac63c-de06-4f2f-99a6-f7baf72ddab2/default/my-function?keyword=${keyword}`)
  .then(function (response) {
    // handle success
    console.log(response.data);
    res.send(response.data)
  })
  .catch(function (error) {
    // handle error
    console.log(error);
    res.status(500).send("Something went wrong")
  })
});


app.listen(port,  () => {
  console.log('app is listening at http://localhost:'+port)
});